### Lecture49 Mar/17/2020

- numpy.random : https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html


- numpy.unique : https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.unique.html#numpy.unique

- numpy.array : https://docs.scipy.org/doc/numpy-1.13.0/glossary.html#term-array



# `Numpy.array`

numpy의 기본 데이터 타입 ndarray를 이용해 numpy에서 다차원 배열 쉽게 생성

다수의 머신러닝 알고리즘이 numpy 기반, 입출력 데이터를 numpy ndarray type으로 사용




## 1차원 배열

In [3]:
import numpy as np
array1 = np.array([1,2,3])
print ('array1 type : ',type(array1))

# 1차원 shape = (열, )
print ('aaray1 array 형태 : ',array1.shape)
print (array1)

array1 type :  <class 'numpy.ndarray'>
[1 2 3]
aaray1 array 형태 변환 :  (3,)
[1 2 3]


## 2차원 배열

In [7]:
array2 = np.array([[1,2,3],
                   [2,3,4]])
print ('array2 type : ', type (array2))

# 2차원 array의 shape = (행, 렬)
print ('array2 shape : ', array2.shape)
print (array2)

array3 = np.array([[1,2,3]])
print ('array3 type : ', type (array3))
print ('array3 shape : ', array3.shape)
print (array3)
print ()
#차원 반환 ndim
print (array1.ndim)
print (array3.ndim)

array2 type :  <class 'numpy.ndarray'>
array2 shape :  (2, 3)
[[1 2 3]
 [2 3 4]]
array3 type :  <class 'numpy.ndarray'>
array3 shape :  (1, 3)
[[1 2 3]]

1
2


## `reshape`
데이터 값은 동일하나, 차원이 달라 오류 발생할 수 있음, 

차원의 차수 변환하여 오류 방지

In [32]:
ar = np.arange(10)
ar1 = ar.reshape(2,5)
ar2 = ar.reshape(5,2)


print (ar, '\n')
print (ar1, '\n')
print (ar2, '\n')

print (ar.reshape(5,2,order='F'), '\n')
print (ar.reshape(5,2,order='A'), '\n')
print (ar.reshape(2,-1), '\n')
# print (ar.reshape(4,-1), '\n')
# 전체 data의 약수가 아니면 에러
print (ar.reshape(-1, 2), '\n')

print (ar2.reshape(10), '\n')
# print (ar.reshape(3,3))
# len보다 작은 행렬로 reshape할 경우 에러 발생

print ('array1 : {}차원, array2 : {}차원 array3 : {}차원'.format(array1.ndim, array2.ndim, array3.ndim))
print (f'array1 : {array1.ndim}차원, array2 : {array2.ndim}차원 array3 : {array3.ndim}차원')

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[0 1 2 3 4 5 6 7 8 9] 

array1 : 1차원, array2 : 2차원 array3 : 2차원
array1 : 1차원, array2 : 2차원 array3 : 2차원


In [34]:
list1 = [1,2,3] ; print (type(list1))
array1 = np.array(list1) ; print (type (array1))
print (array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


서로 다른 datatype 이 섞인 list를 ndarray로 만들 경우

data 크기가 더 큰 datatype으로 일괄 casting

int -> unicode string, int -> float64

In [35]:
list2 = [1,2,'test']
array2 = np.array(list2)
print (array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print (array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


### `astype`

casting

In [46]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print (array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print (array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int64')
print (array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int64


In [45]:
# exe
e = np.array([1.2,2.3,3])
print (e.astype(int), e.astype(int).dtype)
print (e.astype(float), e.astype(float).dtype)

[1 2 3] int64
[1.2 2.3 3. ] float64


## `arange`, `zeros`, `ones`

ndarray를 편리하게 생성

In [47]:
sequence_array = np.arange(10)
print (sequence_array, sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9] int64 (10,)


In [51]:
zero_array = np.zeros((3,2), dtype='float64')
print (zero_array, zero_array.dtype, zero_array.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]] float64 (3, 2)


In [53]:
ones_array = np.ones((3,2), dtype=int)
print (ones_array, ones_array.dtype, ones_array.shape)

[[1 1]
 [1 1]
 [1 1]] int64 (3, 2)


In [56]:
exearr = np.arange(30, dtype = int) ; print (exearr, '\n')
print (exearr.reshape (10,-1), '\n')
print (exearr.reshape (6,-1), '\n')
print (exearr.reshape (-1,15), '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 



In [65]:
#exe
array_e1 = np.arange(21, dtype=int) ; print (array_e1, array_e1.dtype, '\n')
array_e2 = array_e1.reshape(3, 7) ; print (array_e2, '\n')
print (array_e2.reshape(7,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] int64 

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]


## `tolist()`

2차원 이상 array를 list로 변환

In [69]:
arr1 = np.arange(30)
print (arr1, type(arr1), '\n')
arr2d = arr1.reshape(2, 15)
print (arr2d, '\n')
print (arr2d.tolist(),'\n')
print (arr1.reshape(3,2,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] <class 'numpy.ndarray'> 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


### `reshape` 
차원변환

In [71]:
arr1 = np.arange(10)
print (arr1, '\n')

arr2 = arr1.reshape(-1, 5)
print (arr2.shape,'\n', arr2)

[0 1 2 3 4 5 6 7 8 9] 

(2, 5) 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [78]:
arr1 = np.arange(10)
print (arr1, '\n')

print (arr1.reshape(-1, 1), '\n')

# 3차원 배열에서 관습적으로 중복괄호 사용
print (arr1.reshape((1,2,5)), '\n')
print (arr1.reshape((1,2,5)).reshape(-1,1), '\n')

[0 1 2 3 4 5 6 7 8 9] 

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 

[[[0 1 2 3 4]
  [5 6 7 8 9]]] 

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 



In [80]:
# exe
arr3 = arr1.reshape(1, 5,2)
print (arr3, '\n')
print (arr3.reshape(5,2).tolist())

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]] 

[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]


In [102]:
arr1 = np.arange(start=1, stop=10)
print ('arr1 : ', arr1, '\n')

print (arr1[[2,-1]], '\n')
# print (, '\n')
# print (, '\n')

print ('뒤에서 두번째 값 : ',arr1[-2], '\n')

arr1[[0,-1]] = 9, 0
print ('arr1 : ', arr1, '\n')


arr1 :  [1 2 3 4 5 6 7 8 9] 

[3 9] 

뒤에서 두번째 값 :  8 

arr1 :  [9 2 3 4 5 6 7 8 0] 

