## Q.  피마 인디언 당뇨병 예측모델을 만들고 아래사항을 수행하세요.
- diabetes.csv
 - 데이터 세트는 북아메리카 피마 지역 원주민의 Type-2 당뇨병 결과 데이터임.
 - 고립된 지역에서 인디언 고유의 혈통이 지속돼 왔지만 20세기 후반에 들어서면서 서구화된 식습관으로 많은 당뇨 환자 발생
 
- Logistic Regression 을 사용하여 예측모델을 만들고 평가 지표함수를 이용, 정확도, 정밀도, 재현율, F1 Score를 출력

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
db = pd.read_csv('diabetes.csv')
display (db.head())
print (db.info())

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
Pregnancies                 768 non-null int64
Glucose                     768 non-null int64
BloodPressure               768 non-null int64
SkinThickness               768 non-null int64
Insulin                     768 non-null int64
BMI                         768 non-null float64
DiabetesPedigreeFunction    768 non-null float64
Age                         768 non-null int64
Outcome                     768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None


In [65]:
for i in db.columns : 
    print (db[i].unique())
    print (db[i].value_counts().head(10), '\n\n')

[ 6  1  8  0  5  3 10  2  4  7  9 11 13 15 17 12 14]
1    135
0    111
2    103
3     75
4     68
5     57
6     50
7     45
8     38
9     28
Name: Pregnancies, dtype: int64 


[148  85 183  89 137 116  78 115 197 125 110 168 139 189 166 100 118 107
 103 126  99 196 119 143 147  97 145 117 109 158  88  92 122 138 102  90
 111 180 133 106 171 159 146  71 105 101 176 150  73 187  84  44 141 114
  95 129  79   0  62 131 112 113  74  83 136  80 123  81 134 142 144  93
 163 151  96 155  76 160 124 162 132 120 173 170 128 108 154  57 156 153
 188 152 104  87  75 179 130 194 181 135 184 140 177 164  91 165  86 193
 191 161 167  77 182 157 178  61  98 127  82  72 172  94 175 195  68 186
 198 121  67 174 199  56 169 149  65 190]
100    17
99     17
129    14
125    14
111    14
106    14
95     13
108    13
105    13
102    13
Name: Glucose, dtype: int64 


[ 72  66  64  40  74  50   0  70  96  92  80  60  84  30  88  90  94  76
  82  75  58  78  68 110  56  62  85  86  48  44  65 108  55 122 

In [9]:
display (db.corr())

Pregnancies   Glucose  ...       Age   Outcome
Pregnancies                  1.000000  0.129459  ...  0.544341  0.221898
Glucose                      0.129459  1.000000  ...  0.263514  0.466581
BloodPressure                0.141282  0.152590  ...  0.239528  0.065068
SkinThickness               -0.081672  0.057328  ... -0.113970  0.074752
Insulin                     -0.073535  0.331357  ... -0.042163  0.130548
BMI                          0.017683  0.221071  ...  0.036242  0.292695
DiabetesPedigreeFunction    -0.033523  0.137337  ...  0.033561  0.173844
Age                          0.544341  0.263514  ...  1.000000  0.238356
Outcome                      0.221898  0.466581  ...  0.238356  1.000000

[9 rows x 9 columns]

In [0]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, recall_score, f1_score
from sklearn.linear_model import LogisticRegression

In [42]:
y = db['Outcome']
print (type(y))
display (y.head())
x = db.drop(['Outcome'], inplace=False, axis=1)
display (x.head())

xstd = StandardScaler().fit_transform(x)

<class 'pandas.core.series.Series'>


0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0            6      148             72  ...  33.6                     0.627   50
1            1       85             66  ...  26.6                     0.351   31
2            8      183             64  ...  23.3                     0.672   32
3            1       89             66  ...  28.1                     0.167   21
4            0      137             40  ...  43.1                     2.288   33

[5 rows x 8 columns]

In [68]:
xtrain, xtest, ytrain, ytest = train_test_split(xstd, y.astype('category'), test_size=0.2, random_state = 1, stratify=y)

print (f'xtrain : {xtrain.shape}  xtest : {xtest.shape}  ytrain : {ytrain.shape}  ytest : {ytest.shape} ')
print  (ytest.count())

xtrain : (614, 8)  xtest : (154, 8)  ytrain : (614,)  ytest : (154,) 
154


In [0]:
lr = LogisticRegression()
lr.fit(xtrain, ytrain)
# print (type(xtrain))
lrpd = lr.predict(xtest)
# print (type(lrpd))
# print (lrpd)
# print (accuracy_score (ytest, lrpd) )

In [0]:
def model_eval (y_test, pred) : 
    print (f'ConfusionMatrix :\n{confusion_matrix (y_test, pred) }')
    print (f'accuracy_score : {accuracy_score (y_test, pred) }')
    print (f'precision_score : {precision_score (y_test, pred) }')
    print (f'recall_score : {recall_score (y_test, pred) }')
    print (f'F1_score : {f1_score (y_test, pred) }')

In [70]:
model_eval (ytest, lrpd)

ConfusionMatrix :
[[92  8]
 [25 29]]
accuracy_score : 0.7857142857142857
precision_score : 0.7837837837837838
recall_score : 0.5370370370370371
F1_score : 0.6373626373626374


In [62]:
import warnings
warnings.filterwarnings('ignore')

gd = GridSearchCV( estimator=lr, param_grid={'penalty' : [ 'l1', 'l2', 'none' ],
                                             'C' : [ 0.001, 0.01, 0.1, 1, 1.5, 2, ],
                                             }, scoring = 'accuracy', cv=10, refit=True )
gd.fit(xtrain, ytrain)
print (f'best parameter : {gd.best_params_}\nbest score : {gd.best_score_}')

lrbest = gd.best_estimator_
lrbest.fit(xtrain, ytrain)
lrbestpr = lrbest.predict(xtest)
model_eval (ytest, lrbestpr)

best parameter : {'C': 0.001, 'penalty': 'none'}
best score : 0.7752776308831306
ConfusionMatrix :
[[89 10]
 [24 31]]
accuracy_score : 0.7792207792207793
precision_score : 0.7560975609756098
recall_score : 0.5636363636363636
F1_score : 0.6458333333333333


In [0]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(xtrain, ytrain)
dtpr = dt.predict(xtest)



In [54]:
model_eval(ytest, dtpr)

ConfusionMatrix :
[[79 20]
 [27 28]]
accuracy_score : 0.6948051948051948
precision_score : 0.5833333333333334
recall_score : 0.509090909090909
F1_score : 0.5436893203883495


In [0]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(xtrain, ytrain)
rfpr = rf.predict(xtest)

In [56]:
model_eval(ytest, rfpr)

ConfusionMatrix :
[[87 12]
 [18 37]]
accuracy_score : 0.8051948051948052
precision_score : 0.7551020408163265
recall_score : 0.6727272727272727
F1_score : 0.7115384615384616
