In [0]:
import numpy as np
import pandas as pd
import seaborn as sns

# Numpy

In [5]:
np.random.seed (0)
arr = np.random.randint(1,31, size=(5,6))
print (arr)


[[13 16 22  1  4 28]
 [ 4  8 10 20 22 19]
 [ 5 24  7 25 25 13]
 [27  2  7  8 24 15]
 [25 18  6 26 14  9]]
<class 'numpy.ndarray'>


In [9]:
print (type(arr))
print (arr.shape)

<class 'numpy.ndarray'>
(5, 6)


# Pandas

In [0]:
df = pd.DataFrame(np.random.randint(1,31, size=(5,6)), index = [i for i in range(5,0,-1)])
print (df, '\n')
print (df.shape, '\n')
print (df.info(), '\n')
print (df[3].isnull())

In [0]:
titanic = sns.load_dataset('titanic')
titanic.shape
titanic.info()

titanic.isnull().sum()
titanic.notnull().sum()
titanic.age.isnull().sum()

titanic.survived.value_counts()
titanic.deck.value_counts(dropna=True)

titanic_thresh = titanic.dropna(axis=1, thresh=500)
titanic_howall = titanic.dropna (axis = 1, how = 'all')
titanic_howany = titanic.dropna (axis = 1, how = 'any')

titanic_ffill['embark_town'].fillna(method='ffill', inplace=True)
titanic_bfill['embark_town'].fillna(method='bfill', inplace=True)

In [0]:
df_dup = df.duplicated()
df['c2'].duplicated().sum()

df.drop_duplicates()
df['c1'].drop_duplicates()
df.drop_duplicates(subset=['c2']
df.drop_duplicates(subset=['c2', 'c3']

In [0]:
auto_df.horsepower.unique()
auto_df.horsepower.replace('?', np.nan, inplace=True)
auto_df.dropna(subset=['horsepower'], axis=0, inplace=True)
auto_df.horsepower = auto_df.horsepower.astype(float)

auto_df.origin.replace({ 1 : 'USA', 2 : 'EU', 3 : 'JAPAN' }, inplace=True)
auto_df.groupby(['model year','origin'])['kpl'].agg(['min','mean','max', 'count'])

In [0]:
count, bin_dividers = np.histogram(auto_df.horsepower, bins=3)
# bin_names = ['low', 'normal','high']
auto_df['hp_bin'] = pd.cut(x=auto_df.horsepower, bins=bin_dividers, labels=bin_names, include_lowest=True)

In [0]:
hp_dummies = pd.get_dummies(auto_df['hp_bin'])

In [0]:
label_encoder = preprocessing.LabelEncoder()
onehot_labeled = label_encoder.fit_transform(enc_sample)
onehot_reshaped = onehot_labeled.reshape(-1, 1)

onehot_encoder = preprocessing.OneHotEncoder()
onehot_fitted = onehot_encoder.fit_transform(onehot_reshaped)