In [0]:
import numpy as np
import pandas as pd
import seaborn as sns

# Numpy

In [5]:
np.random.seed (0)
arr = np.random.randint(1,31, size=(5,6))
print (arr)


[[13 16 22  1  4 28]
 [ 4  8 10 20 22 19]
 [ 5 24  7 25 25 13]
 [27  2  7  8 24 15]
 [25 18  6 26 14  9]]
<class 'numpy.ndarray'>


In [9]:
print (type(arr))
print (arr.shape)

<class 'numpy.ndarray'>
(5, 6)


# Pandas

In [19]:
df = pd.DataFrame(np.random.randint(1,31, size=(5,6)), index = [i for i in range(5,0,-1)])
print (df, '\n')
print (df.shape, '\n')
print (df.info(), '\n')
print (df[3].isnull())

    0   1   2   3   4   5
5  12   1  12   9  21  11
4  23  12   6  30  29  16
3   9   3  28  20  26  24
2  22  20  15  21  22  30
1   4   4   8  10  10  10 

(5, 6) 

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 5 to 1
Data columns (total 6 columns):
0    5 non-null int64
1    5 non-null int64
2    5 non-null int64
3    5 non-null int64
4    5 non-null int64
5    5 non-null int64
dtypes: int64(6)
memory usage: 280.0 bytes
None 

5    False
4    False
3    False
2    False
1    False
Name: 3, dtype: bool
