#### Q. random.randint()를 사용하여 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])를 출력하세요.

In [17]:
# 풀이
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Q. np.random.rand()를 이용해서 5개의 난수를 생성하고 형변환을 통해서 0보다 큰 정수로 출력하세요.

In [25]:
# 풀이
import random
t1 = np.random.rand(5)*5
print(t1)
t2 = t1.astype('int32')
print(t2)

[3.42995085 3.97345822 4.4083591  2.01605622 2.50087076]
[3 3 4 2 2]


#### Q. arange, zeros, ones를 이용해서 1차원 배열, 2차원 배열(3,3) 을 각각 생성하세요.

In [33]:
a1 = np.arange(3)
print(a1)
print()
z1 = np.zeros((3,3))
print(z1)
print()
o1 = np.ones((3,3))
print(o1)

[0 1 2]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Q. np.random.randint()를 활용 (4,3) 배열 mt1 을 생성하세요

In [18]:
import numpy as np
mt1 = np.random.randint(1,10, size=(4,3))
mt1

array([[4, 6, 5],
       [9, 9, 3],
       [3, 8, 4],
       [1, 1, 2]])

#### Q. mt1을 2x6 행렬로 변환 mt2로 출력하세요.

In [19]:
mt2 = mt1.reshape(2,6)
mt2

array([[4, 6, 5, 9, 9, 3],
       [3, 8, 4, 1, 1, 2]])

#### Q. mt2를 1차원 배열로 변환 후 mt3로 출력하세요.

In [22]:
mt3 = mt2.reshape(-1)
mt3

array([4, 6, 5, 9, 9, 3, 3, 8, 4, 1, 1, 2])

#### Q. arange() 함수를 이용해서  0 ~ 29 정수 배열을 생성하고 2 X 5 X 3 3차원 배열로 변환하세요. 

In [35]:
# 풀이
a1 = np.arange(30)
a1.reshape(2,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

#### Q. 1 ~ 12 연속된 정수 배열을 생성하고 2 X 3 X 2 3차원 배열로 변환 후 list로 출력하세요. 

In [40]:
# 풀이
a1 = np.arange(start=1, stop=13)
print(a1)
print()
a2 = a1.reshape(2,3,2)
print(a2)
print()
a3 = a2.tolist()
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

[[[0, 1], [2, 3], [4, 5]], [[6, 7], [8, 9], [10, 11]]]


#### Q. 0 ~ 29 연속 정수 배열을 생성하고 (10,3) 행렬로 변환 후 인덱싱으로 다음을 출력하세요.
- 12
- [24,25,26]
- 3번째 열 
- 2번째 ~ 5번째 행
- [10,13,16]

In [51]:
# 풀이
a1 = np.arange(30)
a2 = a1.reshape(10,3)
print(a2)
print(a2[4,0])
print(a2[8])
print(a2[:,[2]])
print(a2[1:5])
print(a2[3:6,1])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
12
[24 25 26]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]
 [20]
 [23]
 [26]
 [29]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[10 13 16]


#### Q. 5 ~ 20 연속 정수 배열을 생성하고 불린 인덱싱을 이용하여 짝수만 출력하세요.
#### Q. 동일 배열에서 12보다 큰 정수만 출력하세요.

In [61]:
# 풀이
a1 = np.arange(start = 5, stop = 21)
a2 = a1[(a1 % 2 == 0)]
print(a2)
a3 = a1[a1 > 12]
print(a3)

[ 6  8 10 12 14 16 18 20]
[13 14 15 16 17 18 19 20]


#### Q. random.randint()를 이용해서 10개의 배열을 a1으로 생성후 정렬하세요(내림차순)

In [69]:
# 풀이
np.random.seed(10)
a1 = np.random.randint(10, size= 10)
np.sort(a1)[::-1]

array([9, 9, 9, 8, 4, 1, 1, 0, 0, 0])

#### Q. 1 ~ 21 정수를 랜덤하게 (3,3) 행렬로 생성 후 row, column 방향으로 각각 정렬하세요.

In [71]:
np.random.seed(11)
a1 = np.random.randint(1, 21, size=(3,3))
print(a1)
a1_c = np.sort(a1, axis =1)
print(a1_c)
a1_r = np.sort(a1, axis = 0)
print(a1_r)

[[17 18 14]
 [13  2  8]
 [19 14 17]]
[[14 17 18]
 [ 2  8 13]
 [14 17 19]]
[[13  2  8]
 [17 14 14]
 [19 18 17]]


#### Q. 10에서 20사이의 정수로 구성된 (5,3) 행열을 np.random을 이용해서 nmt1으로 생성하세요.

In [30]:
mt1 = np.random.randint(10,20,size=(5,3))
mt1

array([[18, 15, 11],
       [19, 12, 19],
       [11, 19, 14],
       [11, 19, 18],
       [10, 14, 12]])

#### Q. mt1 행렬을 전치 후 mt2로 출력하세요.

In [28]:
mt2 = mt1.transpose()
mt2

array([[11, 11, 17, 10, 14],
       [16, 11, 15, 15, 13],
       [14, 12, 17, 16, 18]])

#### Q. 6개의 원소로 구성되는 배열을 np.random을 활용하여 생성 mt1으로 출력하세요.

In [37]:
# 풀이
mt = np.random.randint(10, size=6)
mt

array([1, 1, 8, 0, 5, 9])

#### Q. 행벡터 mt를 전치하여 열벡터로 변환하세요.

In [39]:
# 풀이
# 일반적으로 벡터의 전치는 행 벡터를 열 벡터로 혹은 그 반대를 의미
# 대괄호를 두번 사용하면 벡터를 전치할 수 있음
np.array([[1, 1, 8, 0, 5, 9]]).T

array([[1],
       [1],
       [8],
       [0],
       [5],
       [9]])

In [40]:
# (3,3) 행렬 생성
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
type(matrix)

numpy.ndarray

#### Q. 배열 matrix를 broadcasting을 이용하여 다음 배열을 출력하는 연산을 수행하세요. 
array([[101, 202, 303],\
       [104, 205, 306],\
       [107, 208, 309]])


In [11]:
# 풀이
# (3,3) 크기 행렬에 (3,1) 크기 벡터를 더하면 열이 반복됨
matrix + [100,200, 300]

array([[101, 202, 303],
       [104, 205, 306],
       [107, 208, 309]])

#### Q. (3,3) 2차원 배열을 np.random으로 생성하여 mt1으로 저장하고 차원을 구하세요.

In [6]:
# 풀이
import numpy as np
mt1 = np.random.randint(1,10,size=(3,3))
mt1
np.ndim(mt1)

2

#### Q. 아래 두개의 행렬에 대한 덧셈, 뺄셈, 곱셈을 수행하세요

In [12]:
mt1 = np.array([[1, 1, 2],
               [1, 1, 1],
               [3, 3, 4]])

mt2 = np.array([[7, 6, 8],
                [7, 7, 6],
                [8, 7, 8]])

In [15]:
# 풀이
print(mt1 + mt2)
print()
print(mt1-mt2)
print()
print(np.dot(mt1,mt2))

[[ 8  7 10]
 [ 8  8  7]
 [11 10 12]]

[[-6 -5 -6]
 [-6 -6 -5]
 [-5 -4 -4]]

[[30 27 30]
 [22 20 22]
 [74 67 74]]
