In [0]:
import numpy as np

#### Q. random.randint()를 사용하여 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])를 출력하세요.

In [130]:
arr = np.array(np.random.randint(0,1, size=10))
print (arr)

[0 0 0 0 0 0 0 0 0 0]


#### Q. np.random.rand()를 이용해서 5개의 난수를 생성하고 형변환을 통해서 0보다 큰 정수로 출력하세요.

In [147]:
arr = np.array(np.random.rand(5)+1).astype(int)
print (arr)

[1 1 1 1 1]


#### Q. arange, zeros, ones를 이용해서 1차원 배열, 2차원 배열(3,3) 을 각각 생성하세요.

In [0]:
print (np.arange(9), '\n')
print (np.arange(9).reshape(3,3), '\n')
print (np.zeros(9), '\n')
print (np.zeros((3,3)), '\n')
print (np.ones(9), '\n')
print (np.ones((3,3)), '\n')

[0 1 2 3 4 5 6 7 8] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



#### Q. np.random.randint()를 활용 (4,3) 배열 mt1 을 생성하세요

In [149]:
mt1 = np.array(np.random.randint(10, size=12), dtype = int).reshape(4,3)
print (mt1)

[[4 5 0]
 [4 8 5]
 [8 0 2]
 [9 3 2]]


#### Q. mt1을 2x6 행렬로 변환 mt2로 출력하세요.

In [0]:
mt2 = mt1.reshape(2, 6)
print (mt2)

[[4 8 8 5 7 5]
 [4 0 2 8 3 9]]


#### Q. mt2를 1차원 배열로 변환 후 mt3로 출력하세요.

In [0]:
mt3 = mt2.reshape(12,)
print (mt3)

[4 8 8 5 7 5 4 0 2 8 3 9]


#### Q. arange() 함수를 이용해서  0 ~ 29 정수 배열을 생성하고 2 X 5 X 3 3차원 배열로 변환하세요. 

In [0]:
arr = np.arange(30).reshape(2, 5, 3)
print (arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


#### Q. 1 ~ 12 연속된 정수 배열을 생성하고 2 X 3 X 2 3차원 배열로 변환 후 list로 출력하세요. 

In [0]:
arr = np.arange(1, 13, dtype = 'int32').reshape(2,3,2)
print (arr.tolist())

[[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]


#### Q. 0 ~ 29 연속 정수 배열을 생성하고 (10,3) 행렬로 변환 후 인덱싱으로 다음을 출력하세요.
- 12
- [24,25,26]
- 3번째 열 
- 2번째 ~ 5번째 행
- [10,13,16]

In [0]:
arr = np.arange(30).reshape(10,3)
# print (arr)

print (arr[4,0], '\n')
print (arr[-2], '\n')
print (arr[:, 2], '\n')
print (arr[1:5], '\n')
print (arr[3:6, 1], '\n')

12 

[24 25 26] 

[ 2  5  8 11 14 17 20 23 26 29] 

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[10 13 16] 



#### Q. 5 ~ 20 연속 정수 배열을 생성하고 불린 인덱싱을 이용하여 짝수만 출력하세요.

#### Q. 동일 배열에서 12보다 큰 정수만 출력하세요.


In [136]:
arr = np.array(np.arange(5, 21))
print (arr [arr%2==0])
print (arr[arr>12])

[ 6  8 10 12 14 16 18 20]
[13 14 15 16 17 18 19 20]


#### Q. random.randint()를 이용해서 10개의 배열을 a1으로 생성후 정렬하세요(내림차순)

In [142]:
a1 = np.array(np.random.randint(10, size = 10))
print (np.sort(a1)[::-1])

[8 6 4 3 2 2 1 0 0 0]


#### Q. 1 ~ 21 정수를 랜덤하게 (3,3) 행렬로 생성 후 row, column 방향으로 각각 정렬하세요.

In [144]:
arr = np.random.randint(1, 22, size=9).reshape(3,3)
print (arr, '\n')
print (np.sort(arr, axis=1), '\n')
print (np.sort(arr, axis=0), '\n')

[[ 7 18 19]
 [18 11  8]
 [10 21 17]] 

[[ 7 18 19]
 [ 8 11 18]
 [10 17 21]] 

[[ 7 11  8]
 [10 18 17]
 [18 21 19]] 



#### Q. 10에서 20사이의 정수로 구성된 (5,3) 행열을 np.random을 이용해서 mt1으로 생성하세요.

In [0]:
mt1 = np.random.randint(10, 21, size=15).reshape(5,3)
print (mt1)

[[16 18 16]
 [14 18 15]
 [20 14 16]
 [12 12 15]
 [10 11 19]]


#### Q. mt1 행렬을 전치 후 mt2로 출력하세요.

In [0]:
mt2 = mt1.T
print (mt2)

[[16 14 20 12 10]
 [18 18 14 12 11]
 [16 15 16 15 19]]


#### Q. 6개의 원소로 구성되는 배열을 np.random을 활용하여 생성 mt1으로 출력하세요.

In [0]:
mt1 = np.array([np.random.rand(6)])
print (mt1, '\n', mt1.shape)

[[0.35913486 0.68052661 0.84282296 0.28009971 0.53984515 0.89635982]] 
 (1, 6)


#### Q. 행벡터 mt를 전치하여 열벡터로 변환하세요.

In [0]:
mt2 = mt1.transpose()
print (mt2, '\n', mt2.shape)

[[0.05538957]
 [0.86482126]
 [0.4470448 ]
 [0.42878769]
 [0.11164035]
 [0.44025955]] 
 (6, 1)


#### Q. 배열 matrix를 broadcasting을 이용하여 다음 배열을 출력하는 연산을 수행하세요. 
array([[101, 202, 303],\
       [104, 205, 306],\
       [107, 208, 309]])


In [0]:
arr1 = np.array(np.ones((1,1), dtype = int))
arr1 = arr1*([1,2,3])*101 + [[0],[3],[6]]
print (arr1)

[[101 202 303]
 [104 205 306]
 [107 208 309]]


#### Q. (3,3) 2차원 배열을 np.random으로 생성하여 mt1으로 저장하고 차원을 구하세요.

In [0]:
mt1 = np.array(np.random.randint(10, size = 9) ).reshape(3,3)
print (mt1, '\n', mt1.ndim)

[[0 9 5]
 [5 7 2]
 [3 9 6]] 
 2


#### Q. 아래 두개의 행렬에 대한 덧셈, 뺄셈, 곱셈을 수행하세요

In [0]:
mt1 = np.array([[1, 1, 2],
               [1, 1, 1],
               [3, 3, 4]])

mt2 = np.array([[7, 6, 8],
                [7, 7, 6],
                [8, 7, 8]])

In [0]:
print (mt1 + mt2, '\n')
print (mt1 - mt2, '\n')
print (mt1 * mt2)

[[ 8  7 10]
 [ 8  8  7]
 [11 10 12]] 

[[-6 -5 -6]
 [-6 -6 -5]
 [-5 -4 -4]] 

[[ 7  6 16]
 [ 7  7  6]
 [24 21 32]]
