In [0]:
import numpy as np

#### Q. random.randint()를 사용하여 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])를 출력하세요.

In [0]:
arr = np.array(np.random.randint(0,1, size=10))
print (arr)

[0 0 0 0 0 0 0 0 0 0]


#### Q. np.random.rand()를 이용해서 5개의 난수를 생성하고 형변환을 통해서 0보다 큰 정수로 출력하세요.

In [0]:
arr = np.array(np.random.rand(5)+1).astype(int)
print (arr)

[1 1 1 1 1]


#### Q. arange, zeros, ones를 이용해서 1차원 배열, 2차원 배열(3,3) 을 각각 생성하세요.

In [0]:
print (np.arange(9), '\n')
print (np.arange(9).reshape(3,3), '\n')
print (np.zeros(9), '\n')
print (np.zeros((3,3)), '\n')
print (np.ones(9), '\n')
print (np.ones((3,3)), '\n')

[0 1 2 3 4 5 6 7 8] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



#### Q. np.random.randint()를 활용 (4,3) 배열 mt1 을 생성하세요

In [0]:
mt1 = np.array(np.random.randint(10, size=12), dtype = int).reshape(4,3)
print (mt1)

[[0 1 2]
 [2 4 2]
 [2 9 1]
 [0 4 1]]


#### Q. mt1을 2x6 행렬로 변환 mt2로 출력하세요.

In [0]:
mt2 = mt1.reshape(2, 6)
print (mt2)

[[0 1 2 2 4 2]
 [2 9 1 0 4 1]]


#### Q. mt2를 1차원 배열로 변환 후 mt3로 출력하세요.

In [0]:
mt3 = mt2.reshape(12,)
print (mt3)

[0 1 2 2 4 2 2 9 1 0 4 1]


#### Q. arange() 함수를 이용해서  0 ~ 29 정수 배열을 생성하고 2 X 5 X 3 3차원 배열로 변환하세요. 

In [0]:
arr = np.arange(30).reshape(2, 5, 3)
print (arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


#### Q. 1 ~ 12 연속된 정수 배열을 생성하고 2 X 3 X 2 3차원 배열로 변환 후 list로 출력하세요. 

In [0]:
arr = np.arange(1, 13, dtype = 'int32').reshape(2,3,2)
print (arr.tolist())

[[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]


#### Q. 0 ~ 29 연속 정수 배열을 생성하고 (10,3) 행렬로 변환 후 인덱싱으로 다음을 출력하세요.
- 12
- [24,25,26]
- 3번째 열 
- 2번째 ~ 5번째 행
- [10,13,16]

In [0]:
arr = np.arange(30).reshape(10,3)
# print (arr)

print (arr[4,0], '\n')
print (arr[-2], '\n')
print (arr[:, 2], '\n')
print (arr[1:5], '\n')
print (arr[3:6, 1], '\n')

12 

[24 25 26] 

[ 2  5  8 11 14 17 20 23 26 29] 

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[10 13 16] 



#### Q. 5 ~ 20 연속 정수 배열을 생성하고 불린 인덱싱을 이용하여 짝수만 출력하세요.

#### Q. 동일 배열에서 12보다 큰 정수만 출력하세요.


In [0]:
arr = np.array(np.arange(5, 21))
print (arr [arr%2==0])
print (arr[arr>12])

[ 6  8 10 12 14 16 18 20]
[13 14 15 16 17 18 19 20]


#### Q. random.randint()를 이용해서 10개의 배열을 a1으로 생성후 정렬하세요(내림차순)

In [0]:
a1 = np.array(np.random.randint(10, size = 10))
print (np.sort(a1)[::-1])

[9 9 7 7 6 5 5 4 1 0]


#### Q. 1 ~ 21 정수를 랜덤하게 (3,3) 행렬로 생성 후 row, column 방향으로 각각 정렬하세요.

In [0]:
arr = np.random.randint(1, 22, size=9).reshape(3,3)
print (arr, '\n')
print (np.sort(arr, axis=1), '\n')
print (np.sort(arr, axis=0), '\n')

[[ 4 10  5]
 [ 4 15  8]
 [17 21  9]] 

[[ 4  5 10]
 [ 4  8 15]
 [ 9 17 21]] 

[[ 4 10  5]
 [ 4 15  8]
 [17 21  9]] 



#### Q. 10에서 20사이의 정수로 구성된 (5,3) 행열을 np.random을 이용해서 mt1으로 생성하세요.

In [0]:
mt1 = np.random.randint(10, 21, size=15).reshape(5,3)
print (mt1)

[[14 12 14]
 [18 17 11]
 [13 12 15]
 [10 12 15]
 [18 11 12]]


#### Q. mt1 행렬을 전치 후 mt2로 출력하세요.

In [0]:
mt2 = mt1.T
print (mt2)

[[14 18 13 10 18]
 [12 17 12 12 11]
 [14 11 15 15 12]]


#### Q. 6개의 원소로 구성되는 배열을 np.random을 활용하여 생성 mt1으로 출력하세요.

In [0]:
mt1 = np.array([np.random.rand(6)])
print (mt1, '\n', mt1.shape)

[[0.18735886 0.92858238 0.42822218 0.34566424 0.85028897 0.25648987]] 
 (1, 6)


#### Q. 행벡터 mt를 전치하여 열벡터로 변환하세요.

In [0]:
mt2 = mt1.transpose()
print (mt2, '\n', mt2.shape)

[[0.18735886]
 [0.92858238]
 [0.42822218]
 [0.34566424]
 [0.85028897]
 [0.25648987]] 
 (6, 1)


#### Q. 배열 matrix를 broadcasting을 이용하여 다음 배열을 출력하는 연산을 수행하세요. 
array([[101, 202, 303],\
       [104, 205, 306],\
       [107, 208, 309]])


In [0]:
arr1 = np.array(np.ones((1,1), dtype = int))
arr1 = arr1*([1,2,3])*101 + [[0],[3],[6]]
print (arr1)

[[101 202 303]
 [104 205 306]
 [107 208 309]]


#### Q. (3,3) 2차원 배열을 np.random으로 생성하여 mt1으로 저장하고 차원을 구하세요.

In [0]:
mt1 = np.array(np.random.randint(10, size = 9) ).reshape(3,3)
print (mt1, '\n', mt1.ndim)

[[0 1 7]
 [1 6 1]
 [6 0 3]] 
 2


#### Q. 아래 두개의 행렬에 대한 덧셈, 뺄셈, 곱셈을 수행하세요

In [0]:
mt1 = np.array([[1, 1, 2],
               [1, 1, 1],
               [3, 3, 4]])

mt2 = np.array([[7, 6, 8],
                [7, 7, 6],
                [8, 7, 8]])

In [0]:
print (mt1 + mt2, '\n')
print (mt1 - mt2, '\n')
print (mt1 * mt2)

[[ 8  7 10]
 [ 8  8  7]
 [11 10 12]] 

[[-6 -5 -6]
 [-6 -6 -5]
 [-5 -4 -4]] 

[[ 7  6 16]
 [ 7  7  6]
 [24 21 32]]


## random dataset

Youtube 투입 광고비 대비 광고효과(조회수, 좋아요수)

In [0]:
import numpy as np
import pandas as pd

pd.options.display.float_format = '{:,.2f}'.format

vid = np.arange(3000)+1
sr_vid = pd.Series(vid, name='Video ID')

vad = np.random.randint(1, 101, size = 3000)
sr_vad = pd.Series(vad, name='Ad fee(₩1천만)')

vsubs = np.random.randint(10000000, size = 3000)
sr_vsubs = pd.Series(vsubs, name='Subscribers')

vkey = np.random.randint(1, 26, size = 3000)
sr_vkey = pd.Series(vkey, name='Keyword')

vtype = np.random.randint(10, 30, size = 3000)
sr_vtype = pd.Series(vtype, name = 'Type')

vtime = np.random.randint(0,25, size = 3000)
sr_vtime = pd.Series(vtime, name = 'UploadTime')

vwatch = np.random.randint(100, size = 3000)
sr_vwatch = pd.Series(vwatch, name = 'Avg.WatchingTimePerRunningTime')

vclick = np.random.randint(20000000, size = 3000)
sr_vclick = pd.Series(vclick, name = 'Clicks')

vgoods = np.random.randint(vclick)
sr_vgoods = pd.Series(vgoods, name = "Goods")

sr_caratio = pd.Series(vgoods/vad, name = 'Clicks/Ad Ratio')

sr_garatio = pd.Series(vclick/vad, name = 'Goods/Ad Ratio')

sr_score = pd.Series(sr_caratio*1+sr_garatio*10, name = 'Score')

ds = pd.concat ([sr_vid, sr_vad, sr_vsubs, sr_vkey, sr_vtype, sr_vtime, sr_vwatch, sr_vclick, sr_vgoods, sr_caratio, sr_garatio, sr_score], axis = 1)
print (ds)

      Video ID  Ad fee(₩1천만)  Subscribers  Keyword  Type  UploadTime  \
0            1            81      2914007        8    18          24   
1            2            74      9680794        2    26          20   
2            3            44      4112631        1    17          11   
3            4            72      2825574       20    13           2   
4            5            91      8422058       12    26           8   
...        ...           ...          ...      ...   ...         ...   
2995      2996            77      1251402       18    24          17   
2996      2997             2      4176608       15    18           8   
2997      2998            22      5331162       24    22           6   
2998      2999            16      7589680       24    13           7   
2999      3000            96      7328524        8    22          19   

      Avg.WatchingTimePerRunningTime    Clicks     Goods  Clicks/Ad Ratio  \
0                                 44   2589173   1473976  